from BookInfoWebSearchAdaptor import BookInfoWebSearchAdaptor
from AmazonWebSearchAdaptor import AmazonWebSearchAdaptor
from IQBuyWebSearchAdaptor import IQBuyWebSearchAdaptor
from ISBNDbWebSearchAdaptor import ISBNDbWebSearchAdaptor
from LibraryThingWebSearchAdaptor import LibraryThingWebSearchAdaptor
from LiveLibWebSearchAdaptor import LiveLibWebSearchAdaptor
from OpenLibraryWebSearchAdaptor import OpenLibraryWebSearchAdaptor
from LabirintWebSearchAdaptor import LabirintWebSearchAdaptor